users/danilocecci.js
Adicionei as minhas informações
=> Adicionei as informações de Danilo Cecci

users/rudfarlon.js
Adicionado informações do Rud Farlon
=> Adicionei as informações de Rud Farlon

users/gabriel-williamS.js
=> Adicionado aluno gabriel william turma 2 

users/gleicebsouza.js
incluido informacoes das redes sociais #7
=> informacoes-gleice

users/rafaelbpires.js
Adicionar as informações de Rafael Barros Pires (turma 1).
Fix #11
=> chore: adiciona informações

users/danilocecci.js
=> fill info stage2 danilocecci

users/mullerhub.js
Vou adicionar as informações para networking do Murilo Muller (mullerhub) :fix #18
=> Vou adicionar informações do Murilo Muller

styles/User.module.css, users/birobirobiro.js
- Add birobirobiro's info
- Fix challenges cards
Before:
After:
=> chore/fix: add birobirobiro's info and fix challenges styles

users/apolomoraes.js
=> adiciona informações Apolo Moraes

users/gabriel-williams.js
=> Adicionando desafios dos stages

styles/Home.module.css, users/anasilveira9787.js
feat: added CSS scale effect and also my personal card
=> feat: added CSS scale effect and also my personal card

users/dam450.js
Fix #23 - adiciona informações do aluno Evandro Damaso (dam450) da turma 3.
=> Adicionado aluno Evandro Damaso, turma 3

users/mullerhub.js
Stages 01, 02 e 03 adicionados
=> Muller hub

users/ricardodev10.js
=> Adicionei as informações de [ricardodev10]

users/m0nicavaz.js
=> feat: monica vaz info

users/fabioluizz.js
=> Adicionei as informações de FabioLuizz

users/rudfarlon.js
Adicionei as informações dos desafios realizados dentro do programa Explorer, desafio do 1 ao 3.
=> Adiciona informações dos desafios

users/amanciio93.js
Fix #
Adicionado informações até o Stage 05, stage atual do aluno.
=> Adicionado informações sobre amanciio93, turma 05.

users/HenriquedaFonte.js
=> Adicionei as informações de Henrique da Fonte

users/HenriquedaFonte.js
=> FIX: Corrigido o nome do pais

users/rudfarlon.js
=> Adicionar informações

users/robertoSilva.js
#55 informações iniciais de roberto silva turma1
=> informações iniciais de roberto silva turma1

users/danilocecci.js
=> Adicionei informações do stage 3 de Danilo Cecci

pages/index.js
Gera o link da página dos usuários a partir do filename.
=> fix url users

components/Level.jsx, pages/index.js, styles/Home.module.css, styles/Level.module.css
=> add level tag

users/saulocatunda.js
Fix #64 
saulocatunda's personal info added
=> Adicionei as informações de saulocatunda

users/lfoalves.js
Por favor adicione as minhas informações
=> infos de lfoalves

users/viniseven.js
=> Adicionei as informações de viniseven

users/robertoSilva.js
Pequena atualização para corrigir a bandeira do Alagoas (Roberto Silva)
=> Arrumando bandeira do Alagoas(Roberto Silva)

users/madalena-rocha.js
=> Adicionei as informações de madalena-rocha

users/douglaSantoSilva.js
Adição dos links dos desafios do stage 2 e alteração do redirecionamento do Lindedin.
=> Informações stage2 e correção link linkedin

users/lfoalves.js
Por gentileza Valdemir, adicione as minhas informações do stage 2.
=> infos do stage 2 de lfoalves

users/viniseven.js
=> Adicionei informações de viniseven

users/rudfarlon.js
=> Adicionar informações stage 8, 9

users/lfoalves.js
Por favor. Adicione as minhas informações do Stage 03.
=> infos do stage 3 de lfoalves

users/mullerhub.js
Informações adicionais sobre os links/url dos stages sobre o aluno Murilo Muller (mullerhub)
=> Desafios_URL Murilo

users/danilocecci.js
=> Informações do stage 4, 5 e 6 de Danilo Cecci

users/HenricoAngolera.js
=> Adicionei as informações de HenricoAngolera

users/Rrhapsod.js
=> Atualizei as informações do user Renan Rondon

users/lfoalves.js
Por favor Valdemir, adicione as minhas informações dos Stages 4, 5 e 6.
=> infos dos stages 4, 5 e 6 de lfoalves

users/gabriel-williams.js
Adicionando o front e back do desafio final Aluno Gabriel
=> feat: adicionando o front e back desafio final

users/douglaSantoSilva.js
=> adicionei informações stage 4

users/m0nicavaz.js
=> feat: add monica vaz projects

users/eduardonobrega.js
=> Adicionei as informações de eduardonobrega

users/vitorfsousa.js
=> Chore: Add Vitor Sousa's info.

users/gleicebsouza.js, users/valdemirfilho.js
=> Gleice stage2

users/gleicebsouza.js, users/valdemirfilho.js
=> Inclusão dos desafios stage 2 e stage 3

users/gleicebsouza.js
=> add info stage3

users/mullerhub.js
=> ajustes no user

users/diegommagno.js
=> Adicionadas informações de diegommagno

users/lfoalves.js
Por gentilieza Valdemir, adicione as minhas informações do Stage 7 e o Backend do Stage 8
=> infos do stage 7 e backend do stage 8

users/HenriquedaFonte.js
=> Add Info Stage 4

users/HenriquedaFonte.js
=> Add desafio final

users/gksouza.js
Conforme conversa com Valdemir segue meu pull request.
=> Add Grace's information

users/gksouza.js
=> Add informations Stage 2

users/gksouza.js
=> Add infos Stage3

users/gksouza.js
=> Infos Stage4

users/pedro558.js
=> Adicionei as informações de Pedro Afonso

users/lucyanovidio.js
=> Adicionando aluno Lucyan Ovídio turma 1

users/lucyanovidio.js
Adicionei meus links para o Stage 02
=> Adicionando Stage 02

users/lucyanovidio.js
Adicionando Stage 03 Fase 01 (Formulários).
=> Adicionando Stage 03 Fase 01

users/lucyanovidio.js
Meus links para repositório e deploys foram alterados, então atualizei.
=> Atualizando meus links, pois foram alterados

users/CleytonW.js
=> Adicionei as informações de CleytonW

users/saulocatunda.js
Adicionado as informações do stage4 para o usuário SauloCatunda #161
=> Adicionei informações do stage4 no usuário SauloCatunda

users/mullerhub.js
atualizado desafios de mullerhub
=> Adicionado Stage 9/10

users/amandatec.js
=> adicionando a alunaAmanda Oliveira turma 5

users/amandatec.js
=> add link desafio stage7

users/viniseven.js
=> Adicionando aluno Marcus Vinicius

users/apolomoraes.js
Pedido para adicionar meu desafio gitfav, link do codigo e deploy.
=> desafio gitfav

users/apolomoraes.js
Pedido para adicionar informações dos stages 08 09 10 11.
=> Stages 08 09 10 11

users/apolomoraes.js
Pedido para adicionar desafio final do explorer.
=> Desafio final

users/alvesgc.js
=> Adicionei as informações de alvesgc

app/[user]/page.js, app/components/Flag.jsx, app/styles/User.module.css
add flag icon user page and remove skill icons
=> add flag icon user page

app/globals.css
=> fix: remove anchors decoration
